backend:
  name: github
  repo: hack-along/gridsome-boilerplate
  branch: master

media_folder: "static/uploads/events"
public_folder: "/uploads/events"

collections:
  - name: "event"
    label: "Event"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          default: "",
          dateFormat: "YYYY-MM-DD",
          timeFormat: false,
          pickerUtc: true,
        }
      - {
          label: "Start Time (format without seperator eg. 1600 or 1830)",
          name: "start_time",
          default: "0000",
          widget: "string",
        }
      - {
          label: "End Time (format without seperator eg. 1600 or 1830)",
          name: "end_time",
          default: "0000",
          widget: "string",
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          media_library: { config: { multiple: false } },
        }
      - {
          label: "Tags (comma seperated list eg: item1, item2)",
          name: "tags",
          widget: "list",
          collection: "tag",
          valueField: "title",
          searchFields: ["title"],
          displayFields: ["title"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
